services:
  ebacala.com:
    image: ghcr.io/ebacala/ebacala.com:latest
    ports:
      - "8000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s