name: Build website

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  USERNAME: ebacala

jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     # - name: Install SSH Key
      #  uses: webfactory/ssh-agent@v0.7.0
       # with:
        #  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #- name: ZeroTier connection
      #  uses: zerotier/github-action@v1
       # with:
        #  network_id: "${{ secrets.ZEROTIER_NETWORK_ID }}"
        #  auth_token: "${{ secrets.ZEROTIER_AUTH_TOKEN }}"
     # - name: Adding Known Host 
     #   run: ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn generate
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          tags: ghcr.io/${{ env.USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}, ghcr.io/${{ env.USERNAME }}/${{ github.event.repository.name }}:latest
          push: true
        
